{{ config(materialized="table") }}

select 
    GEOLOCATION_ZIP_CODE_PREFIX
  , IF(GEOLOCATION_LAT = 0, NULL, GEOLOCATION_LAT) AS GEOLOCATION_LAT
  , IF(GEOLOCATION_LNG = 0, NULL, GEOLOCATION_LNG) AS GEOLOCATION_LNG
  , TRIM(UPPER(GEOLOCATION_CITY)) AS GEOLOCATION_CITY
  , TRIM(UPPER(GEOLOCATION_STATE)) AS GEOLOCATION_STATE
from 
    data-analyst-prj.ecommerce_raw.geolocation