{{ config(materialized="table") }}

select 
    ORDER_ID
  , CUSTOMER_ID
  , TRIM(UPPER(ORDER_STATUS)) AS ORDER_STATUS
  , TIMESTAMP(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TIMESTAMP
  , TIMESTAMP(ORDER_APPROVED_AT) AS ORDER_APPROVED_AT
  , TIMESTAMP(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_DATE
  , TIMESTAMP(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_DATE
  , TIMESTAMP(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE
from 
    data-analyst-prj.g_drive_javier_ecommerce.orders
where
    ORDER_ID IS NOT NULL
AND CUSTOMER_ID IS NOT NULL