{{ config(materialized="table") }}

select 
    REVIEW_ID
  , ORDER_ID
  , REVIEW_SCORE
  , TRIM(UPPER(REVIEW_COMMENT_TITLE)) AS REVIEW_COMMENT_TITLE
  , TRIM(UPPER(REVIEW_COMMENT_MESSAGE)) AS REVIEW_COMMENT_MESSAGE
  , REVIEW_CREATION_DATE
  , REVIEW_ANSWER_TIMESTAMP
from 
    data-analyst-prj.ecommerce_raw.order_reviews
where
    REVIEW_ID IS NOT NULL
AND ORDER_ID IS NOT NULL